# Form implementation generated from reading ui file 'book.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.book_button = QtWidgets.QPushButton(self.centralwidget)
        self.book_button.setGeometry(QtCore.QRect(270, 430, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.book_button.setFont(font)
        self.book_button.setObjectName("book_button")
        self.room_scroll = QtWidgets.QScrollArea(self.centralwidget)
        self.room_scroll.setGeometry(QtCore.QRect(270, 100, 261, 281))
        self.room_scroll.setWidgetResizable(True)
        self.room_scroll.setObjectName("room_scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 259, 279))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.room_scroll.setWidget(self.scrollAreaWidgetContents)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(270, 390, 261, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateTimeEdit.setFont(font)
        self.dateTimeEdit.setDate(QtCore.QDate(2022, 6, 1))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.book_button.setText(_translate("MainWindow", "Забронировать"))
