# Form implementation generated from reading ui file 'reg_base.ui'
#
# Created by: PyQt6 UI code generator 6.3.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.reg_button = QtWidgets.QPushButton(self.centralwidget)
        self.reg_button.setGeometry(QtCore.QRect(310, 340, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.reg_button.setFont(font)
        self.reg_button.setObjectName("reg_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 300, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.mail_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.mail_edit.setGeometry(QtCore.QRect(310, 300, 221, 20))
        self.mail_edit.setObjectName("mail_edit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 240, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.adress_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.adress_edit.setGeometry(QtCore.QRect(310, 240, 221, 20))
        self.adress_edit.setObjectName("adress_edit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 210, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.name_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_edit.setGeometry(QtCore.QRect(310, 210, 221, 20))
        self.name_edit.setObjectName("name_edit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 270, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.phone_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.phone_edit.setGeometry(QtCore.QRect(310, 270, 221, 20))
        self.phone_edit.setObjectName("phone_edit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.reg_button.setText(_translate("MainWindow", "Зарегистрировать"))
        self.label.setText(_translate("MainWindow", "Почта:"))
        self.label_2.setText(_translate("MainWindow", "Адрес:"))
        self.label_3.setText(_translate("MainWindow", "Название:"))
        self.label_4.setText(_translate("MainWindow", "Телефон:"))
